Modify unicorn to do rolling upgrades

diff --git a/templates/init-unicorn.erb b/templates/init-unicorn.erb
--- a/templates/init-unicorn.erb
+++ b/templates/init-unicorn.erb
@@ -59,10 +59,10 @@ reload)
 	su - $USER -c "$CMD"
 	;;
 upgrade)
-	sig USR2 && sleep 5 && oldsig QUIT && echo "Killing old master" && exit 0
-	echo >&2 "Couldn't upgrade, starting '$CMD' instead"
-	sig QUIT && su - $USER -c "$CMD"
-	;;
+  sig USR2 && sleep 20 && echo upgrade OK && exit 0
+  echo >&2 "Couldn't upgrade, starting '$CMD' instead"
+  sig QUIT && su - $USER -c "$CMD"
+  ;;
 rotate)
 	sig USR1 && echo rotated logs OK && exit 0
 	echo >&2 "Couldn't rotate logs" && exit 1
